cart/urls.py
from django.urls import path, include
from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]


'''The actual path defined in urlpatterns is not directly visible in the front-end templates. 
Instead, Django uses named URL patterns and the {% url %} template tag to dynamically generate the URLs. 
This abstraction allows for more maintainable and flexible code, 
as changes to URL patterns do not require updates to every template where the URL is used.'''
 

e_commerce_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('inventory.urls', namespace='inventory')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
]

'''only for dev environment '''
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from inventory import views

app_name = 'inventory'

urlpatterns = [
    path('inventory/products', views.product_list, name='product_list'),
    path('inventory/<slug:category_slug>', views.product_list, name='product_list_by_category'),
    path('inventory/<int:product_id>/<slug:slug>', views.product_detail, name='product_detail'),
]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('pay/', views.yookassa_webhook, name='yookassa_webhook'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from inventory.models import Product
from cart.cart import Cart
from cart.form import AddProductToCartForm
 

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = AddProductToCartForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],  # form.py properties
            override=cd['override'],  # form.py properties
        )
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = AddProductToCartForm(
            initial={
                'quantity': item['quantity'],
                'override': True,
            },
        )
    return render(
        request,
        'cart/cart_details.html',
        {'cart': cart},
    )

cart/templates/cart/cart_details.html
{% load static %}

{% block title %} cart_detail.html {% endblock %}

{% block content %}
    <h1>In your cart ...</h1>

    <table>

        <thead>
        <tr>
            <th>Image of the meal</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit Price</th>
            <th>Total Price</th>
        </tr>
        </thead>

        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>

                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img
                                    style="width: 100px; height: 100px; object-fit: cover;"
                                    src="
                                        {% if product.image %}
                                            {{ product.image.url }}
                                        {% else %}
                                            {% static "image/no_image.png" %}
                                        {% endif %} "

                                    alt="#"
                            />
                        </a>
                    </td>

                    <td>{{ product.name }}</td>

                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.override }}
                            <input type="submit" value="update">
                            {% csrf_token %}
                        </form>
                    </td>

                    <td>
                        <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                            <input type="submit" value="remove">
                            {% csrf_token %}
                        </form>
                    </td>

                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>

                </tr>

            {% endwith %}
        {% endfor %}

        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }}</td>
        </tr>

        </tbody>

    </table>

    <p class="text-right">
        <a href="{% url 'inventory:product_list' %}">Continue shopping</a>
        <a href="{% url 'orders:order_create' %}">Checkout</a>
    </p>

{% endblock %}