cart/urls.py
from django.urls import path, include
from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]


'''The actual path defined in urlpatterns is not directly visible in the front-end templates. 
Instead, Django uses named URL patterns and the {% url %} template tag to dynamically generate the URLs. 
This abstraction allows for more maintainable and flexible code, 
as changes to URL patterns do not require updates to every template where the URL is used.'''
 

e_commerce_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('inventory.urls', namespace='inventory')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin/', admin.site.urls),
]

'''only for dev environment '''
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from inventory import views

app_name = 'inventory'

urlpatterns = [
    path('inventory/products', views.product_list, name='product_list'),
    path('inventory/<slug:category_slug>', views.product_list, name='product_list_by_category'),
    path('inventory/<int:product_id>/<slug:slug>', views.product_detail, name='product_detail'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} base.html {% endblock %}</title>
{#    <link rel="stylesheet" href="{% static 'css/styles.css' %}">#}
</head>

<body>

<div id="header">
    <a href="{% url 'inventory:product_list' %}" class="logo'">Burgers & Pizza Shop</a>
</div>

<div id="subheader">
    <div class="cart">
        {% with total=cart|length %}
            Cart: <a href="{% url "cart:cart_detail" %}">{{ total }} items</a>
        {% endwith %}
    </div>
</div>

<div id="content">
    {% block content %}  {% endblock %}
</div>

<footer><p>&copy; "Burger & Pizza Shop" since 2024</p></footer>
</body>

</html>